from time import sleep

def loadbar(iteration, total, prefix='', suffix ='',  decimals=1, length=100, fill='>'):
	percent = ('{0:.' + str(decimals) + 'f}').format(100 * (iteration/float(total)))
	filledLength = int(length * iteration // total)
	bar = fill * filledLength + '-' * (length - filledLength)
	print(f'\r{prefix} |{bar}| {percent}% {suffix}', end='\r')
	if iteration == total:
		print()

items = list(range(0, 50))
l = len(items)
loadbar(0, l, prefix='Progress:', suffix='Complete', length=l)
for i, item in enumerate(items):
	sleep(0.1)
	loadbar(i + 1, l, prefix='Progress:', suffix='Complete', length=l)
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
from random import *
import time as t
print('\033[1;32m' + """)
        ========       //\\         []========[] []          
        []            //  \\        []        [] []        
        []           //    \\       []        [] []
        []          //      \\      []========[] []
        []         // =======\\     []    \\      []
        []        //          \\    []     \\     []
        []       //            \\   []      \\    []
        ========//              \\  []       \\   ==========
""")

print('\033[1;34m' + """     
   ================================================= 
   |           Globe Wifi Password Cracker         |
   |                                               |
   |             Coded by: Carl Centino            |
   |                                               |
   =================================================
   """)
print('\033[1;31m' + """)
 Globe At Home Prepaid Wifi   
 """)
name = input('Select Wifi Model' + " [+] ") 
if name =="Globe At Home Prepaid Wifi":print("Connecting To Globe Data Base [*]") 
t.sleep(3)
name = input('Wifi Name' + " [+] ")
t.sleep(3)
print("Scanning Wifi[*]")
t.sleep(2.5)
print("Scanning Done[√]")
t.sleep(2.5)
import random
lower_case = "Anonymous"
numbers = "11223344556677889900"
Use_for = lower_case + numbers
length_for_pass = 8


password ="".join(random.sample(Use_for,length_for_pass))
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(randoTF8YLhpGm.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)

password ="".join(random.sample(Use_for,length_for_pass))
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(randoTF8YLhpGm.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)

password ="".join(random.sample(Use_for,length_for_pass))
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(randoTF8YLhpGm.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)

password ="".join(random.sample(Use_for,length_for_pass))
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(randoTF8YLhpGm.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)

password ="".join(random.sample(Use_for,length_for_pass))
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(randoTF8YLhpGm.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)

password ="".join(random.sample(Use_for,length_for_pass))
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(randoTF8YLhpGm.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)

password ="".join(random.sample(Use_for,length_for_pass))
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(randoTF8YLhpGm.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)

password ="".join(random.sample(Use_for,length_for_pass))
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(randoTF8YLhpGm.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)

password ="".join(random.sample(Use_for,length_for_pass))
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(randoTF8YLhpGm.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)

password ="".join(random.sample(Use_for,length_for_pass))
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(randoTF8YLhpGm.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)

password ="".join(random.sample(Use_for,length_for_pass))
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(randoTF8YLhpGm.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)

password ="".join(random.sample(Use_for,length_for_pass))
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(random.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)
password ="".join(randoTF8YLhpGm.sample(Use_for,length_for_pass))
t.sleep(0.1)
print("Trying Password [*]")
print("Globe",password)